# Generated by Django 5.1 on 2024-08-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
